version: 1.0.{build}
environment:
  NODEJS_VERSION: "4"
services:
- iis
cache:
  - node_modules -> package.json
configuration:
  - AppVeyor
install:
  - ps: install-Product node $env:NODEJS_VERSION
  - npm install
build:
  project: AppVeyor-Protractor-test-app.sln
  verbosity: quiet
  publish_wap: true
test: off
deploy:
- provider: Local
  AppVeyor-Protractor-test-app.deploy_website: true
  AppVeyor-Protractor-test-app.site_name: Test
  AppVeyor-Protractor-test-app.hostname: localhost
  AppVeyor-Protractor-test-app.port: 47602
  AppVeyor-Protractor-test-app.protocol: http
  AppVeyor-Protractor-test-app.remove_files: true
after_deploy:
  - node_modules\.bin\protractor protractor.conf.js
artifacts:
- path: npm-debug.log
  name: npm error log
